### ISSUE TITLE
[Enh] `producer update` or `producer prepare` command

### ISSUE THREAD

**Issue by Faryshta** [producerphp/producer.producer#8]
How about a `producer update` command? when executed
- updates year in license.
- updates generated phpDoc
- updates `CHANGES` file by reading all commits that start with [Enh], [Bug], [BC], [Fix] and add them.
- ~~compiles binaries~~
- Shows you the diff and allows you to configure a commit.
- if commit cancelled the changes are kept but not committed. This allow you to edit something before commit manually or execute `producer release`
- if commit is approved it allows you to choose if tag as release.

**Comment by pmjones** [comment]
Your _library_ projects need to compile binaries for releases?

**Comment by Faryshta** [comment]
not mine.... maybe compile is not the proper word, i mean for what you write on the `bin/` folder

**Comment by pmjones** [comment]
>  i mean for what you write on the bin/ folder

In theory, composer should be moving stuff to the `bin/` folder.

Some background: I do not think Producer should be making changes to the project. It should validate the project as-it-is, and let you know when it thinks something is wrong. That means "generating phpdoc files" would be out, as would changing the LICENSE file. Producer is not a "build" too, per se; it is a "check before releasing" tool.

Now, having said that, I can see where a "producer changes" (as in, "changes since last release") might be good; the user can then pipe that output to CHANGES.md if they like. That would not be an automated modification; the user gets to apply it, or not, as they see fit.

Do you see where I'm coming from here?

**Comment by Faryshta** [comment]
I do see where you come from.

How about a `producer publish` command then? this one will be the equivalent to `producer validate` then allow the user to configure extra commands in `.producer/config`, then execute `producer changes`  and `producer release`?

producer will not do the moficiations itself, it will allow the user to configure any command required for a publication.

**Comment by pmjones** [comment]
That might be do-able. One step at a time, though. If you want to put together a PR for `producer changes` as a starting point, I can review it.

Also, thanks for your interest and assistance!

**Comment by Faryshta** [comment]
ok let me add a new issue for `producer changes` and will work on it on weekend. I will base it on `producer issues` command

**Comment by pmjones** [comment]
Good deal. You might not need `issues` so much as just the local log and tags (whether Git or Hg).

**Comment by pmjones** [comment]
Closing this, as its result appears to be #9 . Let me know if it need to be re-opened.
